# Generated by Django 4.2.7 on 2024-06-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(help_text='Enter phone number in format: +1234567890', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
